GEMINI_KEYS = [
    "YOUR GEMINI API KEY 1",
    'YOUR GEMINI API KEY 2',
    'YOUR GEMINI API KEY 3'
]

EMAIL_ACCOUNT = "YOUR EMAIL ACCOUNT (example@gmail.com)"
EMAIL_PASSWORD = "YOUR PASSWORD APPLICATION"

QR_CODE_API_KEYS = [
    "YOUR API KEY - QR GENERATE"
]